use crate::unipept_communicator::get_names_for_taxa;
use std::collections::HashMap;
use csv::ReaderBuilder;
use serde::Deserialize;


#[derive(Deserialize)]
struct Row {
    id: String,
    score: String,
    row_type: String,
}

/// Read a CSV-file that was produced by the PepGM algorithm and use it to
/// produce a new CSV-file that only contains the taxon-related information
/// and scores. The string produced by this function can be written directly
/// to a valid CSV-file and contains three columns: `taxon_name`, `taxon_id`,
/// and `score`.
///
/// # Arguments
/// * `csv_content` - A CSV-file (as a string) that has been generated by running the PepGM algorithm.
///
/// # Returns
/// A `String` containing CSV rows with the columns: `taxon_name,taxon_id,score`.
pub fn clean_csv(csv_content: String) -> Result<String, Box<dyn std::error::Error>> {
    // Parse CSV input (without headers)
    let mut rdr = ReaderBuilder::new()
        .has_headers(false)
        .from_reader(csv_content.as_bytes());

    let mut tax_ids: Vec<(i32, f32)> = Vec::new();

    for result in rdr.deserialize() {
        let record: Row = result?;
        if record.row_type == "taxon" {
            if let (Ok(id), Ok(score)) = (record.id.parse::<i32>(), record.score.parse::<f32>()) {
                tax_ids.push((id, score));
            }
        }
    }

    // Sort by score ascending
    tax_ids.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap());

    // Collect all taxon IDs for name lookup
    let ids: Vec<i32> = tax_ids.iter().map(|(id, _)| *id).collect();
    let name_mapping: HashMap<i32, String> = get_names_for_taxa(&ids)
        .map_err(|e| format!("Failed to retrieve taxon names: {}", e))?;

    // Build CSV output
    let mut lines: Vec<String> = Vec::new();
    lines.push("taxon_name,taxon_id,score".to_string());

    for (id, score) in tax_ids {
        if let Some(name) = name_mapping.get(&id) {
            lines.push(format!("{},{},{}", name, id, score));
        }
    }

    Ok(lines.join("\n"))
}