name: Build Wheels

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'peptonizer_rust/dist/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: peptonizer_rust
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: dtolnay/rust-toolchain@stable

      - uses: PyO3/maturin-action@v1
        with:
          command: build
          manylinux: auto
          working-directory: peptonizer_rust
          args: --release --out dist

      - name: Commit wheels
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/*.whl
          git commit -m "Update wheels for ${{ matrix.os }} [skip ci]" || echo "No changes"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
