name: Build Wheels

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'peptonizer_rust/dist/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          
          - os: macos-13
            target: x86_64-apple-darwin
            
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: peptonizer_rust
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: docker/setup-qemu-action@v3

      - uses: PyO3/maturin-action@v1
        with:
          command: build
          manylinux: auto
          working-directory: peptonizer_rust
          args: --release --out dist --target ${{ matrix.target }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.target }}
          path: peptonizer_rust/dist/*.whl

  commit-wheels:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy wheels into repo
        run: |
          mkdir -p peptonizer_rust/dist
          find artifacts -name "*.whl" -exec cp {} peptonizer_rust/dist/ \;

      - name: Commit wheels
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -f peptonizer_rust/dist/*.whl

          git commit -m "Update wheels [skip ci]" || echo "Generate wheel files"

          git push origin HEAD:${GITHUB_REF#refs/heads/}
